"""
Django settings for jobSearch project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
from decouple import config
from kombu import Queue, Exchange

BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["http://localhost:4200/",]
AUTH_USER_MODEL = "accounts.User"

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "accounts",
    "jobs",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "django_celery_beat",     # tâches périodiques gérées en base
    "django_celery_results",  # stockage des résultats en base
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "jobSearch.urls"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
}

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "jobSearch.wsgi.application"

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Redis local (développement)
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://localhost:6379/0")

# Stocke les résultats des tâches en base Django (optionnel mais utile pour le debug)
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", "django-db")

#  SÉRIALISATION

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"

#  TIMEZONE

CELERY_TIMEZONE = "Africa/Douala"   # adapte selon ton serveur
CELERY_ENABLE_UTC = True

#  FIABILITÉ & RETRY

# Acquitte la tâche APRÈS exécution (pas avant) → évite la perte en cas de crash
CELERY_TASK_ACKS_LATE = True

# Renvoie la tâche dans la queue si le worker meurt pendant l'exécution
CELERY_TASK_REJECT_ON_WORKER_LOST = True

# Timeout d'une tâche (secondes) — tue les tâches bloquées
CELERY_TASK_SOFT_TIME_LIMIT = 60    # lève SoftTimeLimitExceeded
CELERY_TASK_TIME_LIMIT = 120   # kill dur après 2 min

# Limite le nombre de tâches par worker avant redémarrage (évite les fuites mémoire)
CELERY_WORKER_MAX_TASKS_PER_CHILD = 500

#  QUEUES (priorités)

# Déclare 3 queues : critique (emails auth), default, low (rappels périodiques)



default_exchange = Exchange("default", type="direct")

CELERY_TASK_QUEUES = (
    Queue("critical", default_exchange, routing_key="critical"),
    Queue("default",  default_exchange, routing_key="default"),
    Queue("low",      default_exchange, routing_key="low"),
)
CELERY_TASK_DEFAULT_QUEUE        = "default"
CELERY_TASK_DEFAULT_EXCHANGE     = "default"
CELERY_TASK_DEFAULT_ROUTING_KEY  = "default"

# Routage des tâches vers les bonnes queues
CELERY_TASK_ROUTES = {
    # Emails critiques (auth) → queue critique
    "accounts.tasks.send_password_reset_email":    {"queue": "critical"},
    # Notifications jobs → queue par défaut
    "jobs.tasks.send_new_application_email":        {"queue": "default"},
    "jobs.tasks.send_application_status_email":     {"queue": "default"},
    # Rappels périodiques → queue basse priorité
    "jobs.tasks.send_deadline_reminders_task":      {"queue": "low"},
}

#  TÂCHES PÉRIODIQUES (Celery Beat)

CELERY_BEAT_SCHEDULE = {
    # Envoie les rappels d'expiration chaque jour à 8h00
    "send-deadline-reminders-daily": {
        "task": "jobs.tasks.send_deadline_reminders_task",
        "schedule": timedelta(days=1),
        "options": {"queue": "low"},
        # Pour fixer l'heure exacte, utiliser crontab :
        # "schedule": crontab(hour=8, minute=0),
    },
}
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL")
FRONTEND_URL = config("FRONTEND_URL")
EMAIL_BACKEND = config("EMAIL_BACKEND")
EMAIL_HOST = config("EMAIL_HOST")
EMAIL_PORT = config("EMAIL_PORT")
EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=True)
EMAIL_HOST_USER = config("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")


