# Generated by Django 6.0.6 on 2026-06-10 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Intitulé du poste"),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "location",
                    models.CharField(max_length=100, verbose_name="Localisation"),
                ),
                (
                    "remote",
                    models.BooleanField(
                        default=False, verbose_name="Télétravail possible"
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("CDI", "CDI"),
                            ("CDD", "CDD"),
                            ("STAGE", "Stage"),
                            ("FREELANCE", "Freelance"),
                        ],
                        max_length=20,
                        verbose_name="Type de contrat",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Ouverte"), ("closed", "Fermée")],
                        default="open",
                        max_length=10,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "experience_required",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Expérience requise (années)"
                    ),
                ),
                (
                    "education_level_required",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bac", "Baccalauréat"),
                            ("bac+2", "Bac+2 (BTS / DUT)"),
                            ("bac+3", "Bac+3 (Licence)"),
                            ("bac+5", "Bac+5 (Master / Ingénieur)"),
                            ("bac+8", "Bac+8 (Doctorat)"),
                            ("other", "Autre"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="Niveau d'études requis",
                    ),
                ),
                (
                    "salary_min",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Salaire minimum (€/an)"
                    ),
                ),
                (
                    "salary_max",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Salaire maximum (€/an)"
                    ),
                ),
                (
                    "deadline",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date limite de candidature"
                    ),
                ),
                (
                    "posted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Publié le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="accounts.company",
                        verbose_name="Entreprise",
                    ),
                ),
                (
                    "skills_required",
                    models.ManyToManyField(
                        blank=True,
                        related_name="jobs",
                        to="accounts.skill",
                        verbose_name="Compétences requises",
                    ),
                ),
            ],
            options={
                "verbose_name": "Offre d'emploi",
                "verbose_name_plural": "Offres d'emploi",
                "ordering": ["-posted_at"],
            },
        ),
        migrations.CreateModel(
            name="FavoriteJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "saved_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Sauvegardé le"
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_jobs",
                        to="accounts.candidate",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "verbose_name": "Offre favorite",
                "verbose_name_plural": "Offres favorites",
                "ordering": ["-saved_at"],
            },
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cover_letter",
                    models.TextField(
                        blank=True, null=True, verbose_name="Lettre de motivation"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("accepted", "Acceptée"),
                            ("rejected", "Refusée"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Candidaté le"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="accounts.candidate",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "verbose_name": "Candidature",
                "verbose_name_plural": "Candidatures",
                "ordering": ["-applied_at"],
            },
        ),
        migrations.CreateModel(
            name="JobView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Nombre de vues"
                    ),
                ),
                (
                    "first_viewed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Premier vue le"
                    ),
                ),
                (
                    "last_viewed_at",
                    models.DateTimeField(auto_now=True, verbose_name="Dernière vue le"),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="viewed_jobs",
                        to="accounts.candidate",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vue d'offre",
                "verbose_name_plural": "Vues d'offres",
            },
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["status", "posted_at"], name="jobs_job_status_60011a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["location"], name="jobs_job_locatio_8b2f8c_idx"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["contract_type"], name="jobs_job_contrac_be1848_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["remote"], name="jobs_job_remote_075727_idx"),
        ),
        migrations.AddConstraint(
            model_name="favoritejob",
            constraint=models.UniqueConstraint(
                fields=("job", "candidate"), name="unique_favorite_job"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(fields=["status"], name="jobs_applic_status_f83260_idx"),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["applied_at"], name="jobs_applic_applied_207476_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="application",
            constraint=models.UniqueConstraint(
                fields=("job", "candidate"), name="unique_application"
            ),
        ),
        migrations.AddConstraint(
            model_name="jobview",
            constraint=models.UniqueConstraint(
                fields=("job", "candidate"), name="unique_job_view"
            ),
        ),
    ]
